algoritmo "somanumeros"
// Função : O usuário digita quantos números quiser e o algoritmo fecha quando digitar o número 0
// Autor : Thiago de Olivera Freitas
// Data : 12/08/2021
var

num, result, cont: inteiro

inicio
num<- 1
result<- 0
Enquanto num <> 0 faca
   Escreva (" Digite um número: ")
   leia (num)
   result<- result + num
   Escreval (" ")
fimenquanto
Escreval (" A soma de todos os números deu: ",result)

fimalgoritmo
